### ISSUE TITLE
关于kinetics数据集的训练

### ISSUE THREAD

**Issue by 15762260991** [czhaneva/MST-GCN#1]
大佬您好！
@czhaneva 
请问您是否能提供kinetics数据集的yaml文件及运行指令呢？小白将不胜感激！

**Comment by czhaneva** [comment]
你好，你可以参照ST-GCN中关于kinetics数据集训练的yaml文件来修改。

**Comment by czhaneva** [comment]
> 大佬您好！ @czhaneva 请问您是否能提供kinetics数据集的yaml文件及运行指令呢？小白将不胜感激！

https://github.com/yysijie/st-gcn/blob/master/config/st_gcn/kinetics-skeleton/train.yaml
